name: afc_mobile
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^1.6.7
  sembast: ^2.4.2
  loading_overlay: ^0.2.1
  font_awesome_flutter: ^8.8.1
  cupertino_icons: ^0.1.2
  jaguar_jwt: ^2.1.6
  dio: ^3.0.9
  equatable: ^1.1.1
  flutter_bloc: ^4.0.0
  get_it: ^4.0.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.6+3
  image_picker: ^0.6.7+2
  intl: ^0.16.1
  injectable: ^0.3.0
  meta: ^1.1.8
  photo_view: ^0.9.2
  cached_network_image: ^2.1.0+1
  flutter_exif_rotation: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  freezed: ^0.10.6
  injectable_generator: ^0.3.4

flutter:
  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Bold.ttf
        - asset: assets/fonts/Manrope-ExtraBold.ttf
        - asset: assets/fonts/Manrope-ExtraLight.ttf
        - asset: assets/fonts/Manrope-Light.ttf
        - asset: assets/fonts/Manrope-Medium.ttf
        - asset: assets/fonts/Manrope-Regular.ttf
        - asset: assets/fonts/Manrope-SemiBold.ttf

    - family: Comic Neue
      fonts:
        - asset: assets/fonts/ComicNeue-Italic.ttf
        - asset: assets/fonts/ComicNeue-Light.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
        - asset: assets/fonts/ComicNeue-BoldItalic.ttf
        - asset: assets/fonts/ComicNeue-Regular.ttf

  uses-material-design: true
