name: afc_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  jaguar_jwt: ^2.1.6
  dio: ^3.0.9
  equatable: ^1.1.0
  flutter_bloc: ^3.2.0
  get_it: ^4.0.1
  flutter_spinkit: ^4.1.2+1
  shared_preferences: ^0.5.6+3
  image_picker: ^0.6.4
  intl: ^0.16.1
  injectable: ^0.3.0
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  injectable_generator: ^0.3.4
  build_runner: ^1.8.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/icons/error.png
    - assets/icons/robot.png
    - assets/icons/intro.jpg
    - assets/icons/login.png
    - assets/login_background.png
    - assets/register_background.png
    - assets/avatar_placeholder.png
    - assets/splash_screen_background.png
    - assets/course_background.png
    - assets/classroom.jpg

  fonts:
    - family: Pacifito
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Comic Neue
      fonts:
        - asset: assets/fonts/ComicNeue-Italic.ttf
        - asset: assets/fonts/ComicNeue-Light.ttf
        - asset: assets/fonts/ComicNeue-Bold.ttf
        - asset: assets/fonts/ComicNeue-BoldItalic.ttf
        - asset: assets/fonts/ComicNeue-Regular.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
